### ISSUE TITLE
TODOs from Leif

### ISSUE THREAD

**Issue by sadamov** [mllam/neural-lam#80]
Here's the monster TODO (completed items removed) 💪 :

- [x] **Update the whole `README.md`**  
    - https://github.com/mllam/neural-lam/pull/66#discussion_r1721735759
        - [x] Remove diagram that describes processing before training
    - https://github.com/mllam/neural-lam/pull/66#discussion_r1730396364
        - [x] Remove “format of data directory” section
    - https://github.com/mllam/neural-lam/pull/66#discussion_r1730396145
        - [x] Update README on pre-processing
    - https://github.com/mllam/neural-lam/pull/66#discussion_r1730047130
        - [x] Explain weighting

_Originally posted by @leifdenby in https://github.com/mllam/neural-lam/issues/66#issuecomment-2379421635_

**Comment by khintz** [comment]
I think I may not know enough about what the missing tasks are - I have just based my work on Leif PR. But of course I can take a look at them also.
Are we in a hurry to get this in ASAP, or would it make sense to wait until Leif is back on November 4?

**Comment by joeloskarsson** [comment]
As this is important for continued research work for me and @sadamov I think we do indeed want to get this finished ASAP. So any help with this is appreciated :smile: 

Many of the TODO-points are quite small changes, that should be fairly easy to understand from the linked comments. Otherwise just ping me for clarifications. Some changes might be a bit trickier but those can be left to me or @leifdenby when he gets back.

**Comment by sadamov** [comment]
I made good progress this week so far and the remaining items look doable. It would be nice to at least merge everything into the main PR from Leif (he gave us push-access to his repo), next week. Then we can run some "real-life" tests and carry out final reviews there. Once Leif is back he can double-check the changes and push the button to merge :record_button: that would be my goal.

**Comment by khintz** [comment]
Ah yes, of course, Joel I didn't think of that. 
I can definitely help with the easier things, like the "Update README on pre-processing", and help testing along the way.

**Comment by joeloskarsson** [comment]
Putting this here since there is no way to navigate the actual PR anymore...

 Left to fix:

- [x] https://github.com/mllam/neural-lam/pull/66#discussion_r1831213731
- [x] https://github.com/mllam/neural-lam/pull/66#discussion_r1831264008
- [x] https://github.com/mllam/neural-lam/pull/66#discussion_r1832507291

\+ I am going to read through the README.

**Comment by joeloskarsson** [comment]
Everything here is done now, so closing this.
